### ISSUE TITLE
it fails to writeHead for cookie

### ISSUE THREAD

**Issue by wootaek-py** [mpneuried/connect-redis-sessions#13]
bellow is simple testing code using express 4.14.0

index.js
```js
{

	/* package.json
	{
	  "name": "test_session",
	  "version": "1.0.0",
	  "description": "",
	  "main": "index.js",
	  "author": "",
	  "license": "ISC",
	  "dependencies": {
		"connect-redis-sessions": "^1.2.0",
		"cookie-parser": "^1.4.3",
		"express": "^4.14.0"
	  }
	}

	*/

	// get the modules 
	var http = require('http');
	var express = require( "express" );
	var cookieParser = require( "cookie-parser" );
	var ConnectRedisSessions = require( "connect-redis-sessions" );
	var app = express();
	 
	 
	// configute express 
	app
		.use( express.query() )
		.use( cookieParser() )
		.use( ConnectRedisSessions( { app: "myappname"} ) )
	 
	// listen for requests 
	app.use( function( req, res ){
		
		console.log( '> req.session.id:',  req.session.id ); // <--- always null
		
		// ------ this code fails to write cookie -----------
		req.session.upgrade( 7 );
		res.end( "Hello express redis sessions" );
		
		/* ------ this code works good -----------
		req.session.upgrade( 7, (err) => {
			res.end( "Hello express redis sessions" );
		} );
		*/
		
		
	});


	const server = http.createServer( app );
	server.listen( '80' );

}
```

/node_modules/connect-redis-sessions/lib/sessionhandler.js
```js
{

	SessionHandler.prototype.generate = function (req, token, id, ttl) {

		  console.log( "@ generate:", token, id, ttl );

		  var res, _writeHead;
		  req.sessionID = token;
		  req.session = new SessionObject( this, req, this._redisToSession( {
			  id: id,
			  ttl: ttl,
			  ip: this._getRequestIP( req )
		  } ) );
		  res = req.res;

		  _writeHead = res.writeHead;

		  res.writeHead = (function (_this) {

			  console.log( "@ res.writeHead()" );

			  // @@@@@@@ problem is this part @@@@@@@
			  // bellow function never runs when callback function is null
			  return function () {
				  _this._setCookie( req );
				  _writeHead.apply( res, arguments );
			  };
		  })( this );
	  };

}
```

**Comment by wootaek-py** [comment]
there's console log on first upgrade function call

{ invalidValue: d must containt at least one key.
    at RedisSessions._handleError (E:\_DELETE_ME_\test_session\node_modules\redis-sessions\index.js:457:14)
    at RedisSessions._handleError (E:\_DELETE_ME_\test_session\node_modules\redis-sessions\index.js:17:57)
    at RedisSessions._validate (E:\_DELETE_ME_\test_session\node_modules\redis-sessions\index.js:605:18)
    at RedisSessions.set (E:\_DELETE_ME_\test_session\node_modules\redis-sessions\index.js:343:20)
    at RedisSessions.set (E:\_DELETE_ME_\test_session\node_modules\redis-sessions\index.js:17:57)
    at SessionHandler.module.exports.SessionHandler.set (E:\_DELETE_ME_\test_session\node_modules\connect-redis-sessions\lib\sessionhandler.js:252:16)
    at SessionHandler.set (E:\_DELETE_ME_\test_session\node_modules\connect-redis-sessions\lib\sessionhandler.js:3:61)
    at Session.module.exports.Session.save (E:\_DELETE_ME_\test_session\node_modules\connect-redis-sessions\lib\sessionobject.js:104:20)
    at Session.save (E:\_DELETE_ME_\test_session\node_modules\connect-redis-sessions\lib\sessionobject.js:3:61)
    at ServerResponse.res.end (E:\_DELETE_ME_\test_session\node_modules\connect-redis-sessions\lib\index.js:57:27)
  name: 'invalidValue',
  message: 'd must containt at least one key.' }

**Comment by mpneuried** [comment]
Hi, this is a Problem with [redis-sessions](https://github.com/smrchy/redis-sessions), because i requires at least one key within the `d` value.
I opened issue redis-sessions/issues#29 to address this problem so d will become optional and not place an error inside the console

**Comment by mpneuried** [comment]
The change should be not to call `redisSessions.set` only if there is a change.
Will come with the next version

**Comment by mpneuried** [comment]
see version `1.3.2`
